name: test_coverage
description: Command line utility to run tests in Dart VM and collect coverage data.
version: 0.3.0+1
homepage: https://github.com/pulyaevskiy/test-coverage
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: ">=2.5.0 <3.0.0"

executables:
  test_coverage:

dependencies:
  coverage: ^0.13.3
  path: ^1.6.4
  lcov: ^5.4.0
  glob: ^1.1.7
  args: ^1.5.2

dev_dependencies:
  test: ^1.9.1
  pedantic: ^1.8.0+1
